const pList01 = [
    {
        index:1,
        ko:"아가타",
        en:"AGATHA",
        img:"agatha.jpg"
    },
    {
        index:2,
        ko:"아가타",
        en:"AGATHA",
        img:"agatha.jpg"
    },
    {
        index:3,
        ko:"아가타",
        en:"AGATHA",
        img:"agatha.jpg"
    },
    {
        index:4,
        ko:"아가타",
        en:"AGATHA",
        img:"agatha.jpg"
    },
    {
        index:5,
        ko:"아가타",
        en:"AGATHA",
        img:"agatha.jpg"
    },
    {
        index:6,
        ko:"아가타",
        en:"AGATHA",
        img:"agatha.jpg"
    },
    {
        index:7,
        ko:"아가타",
        en:"AGATHA",
        img:"agatha.jpg"
    },
  
]